{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimisee.secretName" . }}
  labels:
    {{- include "mimisee.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}

